### PR TITLE
Task.04 - Merge mongoose schemas and updated connection.js

### LINKED ISSUE #7: Task.03 - Create database with tables enabling login for students
Create a student table with the following columns: student ID, student name, student password.

### LINKED ISSUE #13: Task.04 - Create express route for student login
- Develop a secure express route to handle student login requests
- Validate login input (email/username and password)
- Handle potential login failures, such as incorrect credentials or missing fields, by returning appropriate error messages

### PR DESCRIPTION
**Pull request by sasha-klnd**
This commit of the Task.04 branch includes the mongoose schema files and the updated version of connection.js to work with mongoose

### CODE REVIEW

File: server/db/schemas/section.js [hunk 1]
```diff
@@ -0,0 +1,13 @@
+import mongoose, { Schema } from "mongoose";
+
+const sectionSchema = new Schema(
+    {
+        students: [String],
+        course: String,
```
Comment (Vinuyans) [inline server/db/schemas/section.js]: maybe change the names to student_ids and course_id to be clearer

File: server/db/schemas/course.js [hunk 2]
```diff
@@ -0,0 +1,14 @@
+import mongoose, { Schema } from "mongoose";
+
+const courseSchema = new Schema(
+    {
+        course_id: String,
+        number: String,
+        dept: String,
+        prof: String,
```
Comment (Vinuyans) [inline server/db/schemas/course.js]: prof_id would be clearer here as well

File: server/db/schemas/course.js [hunk 3]
```diff
@@ -0,0 +1,14 @@
...
+    },
+    { collections:"Users", queryString:true }
```
Comment (Vinuyans) [inline server/db/schemas/course.js]: Should this be collections: "Courses" ?

**Comment by Vinuyans** [comment]
Your Schemas also serve as the "database" the API uses so I linked #7 to this PR as well

**Review by Vinuyans — APPROVED** [review]
lgtm
