### PR TITLE
Task.09 - Create express route for teacher login

### LINKED ISSUE #11: Task.09 - Create express route for teacher login
- Develop a secure express route to handle teacher login requests
- Validate login input (email/username and password)
- Handle potential login failures, such as incorrect credentials or missing fields, by returning appropriate error messages

### PR DESCRIPTION
**Pull request by srabm**
Closes #11

### CODE REVIEW

File: server/routes/teacherRegistration.js [hunk 1]
```diff
@@ -0,0 +1,58 @@
...
+teacherRouter.post("/", async(req,res) => {
+    if (req.body !=null && req.body.fname != null && req.body.lname != null && req.body.user_id != null && req.body.pw != null){
+        const newUser = new User({
+            fname: req.body.fname,
+            lname: req.body.lname,
+            role: "teacher",
+            user_id: req.body.user_id,
+            pw: req.body.pw
+        });
+            const pwValidated = await validatePassword(req.body.pw);
```
Comment (Marian-Hristov) [inline server/routes/teacherRegistration.js]: `validatePassword` is not async, so you don't need to await it

File: server/routes/api.js [hunk 2]
```diff
@@ -1,4 +1,7 @@
 import express from "express";
+import teacherRegistration from "./teacherRegistration.js";
+import teacherLogin from "./teacherLogin.js";
+import { ObjectId } from "mongodb";
```
Comment (Marian-Hristov) [inline server/routes/api.js]: this line should be removed

File: server/routes/teacherRegistration.js [hunk 3]
```diff
@@ -0,0 +1,58 @@
...
+
+function validatePassword(pw){
+    return /[A-Z]/       .test(pw) &&
+           /[a-z]/       .test(pw) &&
+           /[0-9]/       .test(pw) &&
+           /[^A-Za-z0-9]/.test(pw) &&
+           pw.length > 11;
+}
+
+teacherRouter.post("/", async(req,res) => {
```
Comment (Marian-Hristov) [inline server/routes/teacherRegistration.js:26]: this is not a blocker and should be in another PR, but the route should be defined here and not in api.js

File: server/routes/teacherRegistration.js [hunk 4]
```diff
@@ -0,0 +1,58 @@
...
+      return false; 
+    }
+  }
+
+function validatePassword(pw){
+    return /[A-Z]/       .test(pw) &&
+           /[a-z]/       .test(pw) &&
+           /[0-9]/       .test(pw) &&
+           /[^A-Za-z0-9]/.test(pw) &&
+           pw.length > 11;
```
Comment (Marian-Hristov) [inline server/routes/teacherRegistration.js]: you mention on line 47 that the password should be above 10 characters however this checks for a length longer than 11

File: server/routes/teacherRegistration.js [hunk 5]
```diff
@@ -0,0 +1,58 @@
...
+            if  (pwValidated && idValidated) {
+                await newUser.save()
+                .then(() => res.status(200).send(newUser))
+                .catch((error)=> res.status(500).send("DB upload failed"));
+                    
+            } else {
+                if (!idValidated) {
+                    res.status(400).send("This user ID is already in use by another account. Please choose a different one or log into your existing account.");
+                }
+                if (!pwValidated){
```
Comment (Marian-Hristov) [inline server/routes/teacherRegistration.js:46]:
```suggestion
                else if (!pwValidated){
```
For readability, you might want to change this to the suggestion I gave since it is hard to understand that the else will execute when both ifs fail

**Review by Marian-Hristov — CHANGES_REQUESTED** [review]

File: server/routes/teacherRegistration.js (hunk 5 above)
Comment (srabm) [reply server/routes/teacherRegistration.js:46]: i agree with the change, can you do it for me as im not available rn

Comment (Marian-Hristov) [reply server/routes/teacherRegistration.js:46]: we can change it later, it doesn't need a full commit

**Review by Marian-Hristov — APPROVED** [review]

**Review by Vinuyans — APPROVED** [review]
lgtm
